#!/usr/bin/env bash
# Gaps check: run Tracker smoke/tests, write GAPS.md from failures or "No gaps".
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
GAPS="$ROOT/GAPS.md"

run_tracker_smoke() {
  local dir="$ROOT/initiative-1-tracker/tracker"
  if [ ! -d "$dir" ]; then echo "skip (no tracker)"; return 0; fi
  (cd "$dir" && node index.js 2>&1) | head -1
}

FAILED=""
OUT=""

# 1) Tracker smoke
if [ -d "$ROOT/initiative-1-tracker/tracker" ]; then
  if (cd "$ROOT/initiative-1-tracker/tracker" && node index.js 2>&1) | grep -q "Tracker"; then
    OUT="${OUT}- Tracker smoke: OK\n"
  else
    FAILED="${FAILED}- Tracker smoke failed\n"
  fi
fi

# 2) Optional: node collect (no feed URL → 0 signals is OK)
if [ -d "$ROOT/initiative-1-tracker/tracker" ]; then
  if (cd "$ROOT/initiative-1-tracker/tracker" && node index.js collect 2>&1) | grep -q "Collected"; then
    OUT="${OUT}- Tracker collect: OK\n"
  else
    OUT="${OUT}- Tracker collect: run (no feed URL → 0 signals is OK)\n"
  fi
fi

# Write GAPS.md
{
  echo "# Gaps"
  echo ""
  echo "*(Generated by \`scripts/gaps-check.sh\`. Do not edit by hand.)*"
  echo ""
  if [ -n "$FAILED" ]; then
    echo "## Failures"
    echo ""
    printf "%b" "$FAILED"
    echo ""
    echo "## Checks run"
    printf "%b" "$OUT"
  else
    echo "- No automated gaps. Last check: $(date -u +%Y-%m-%dT%H:%MZ)."
    echo ""
    printf "%b" "$OUT"
  fi
} > "$GAPS"

echo "Gaps check done. See $GAPS"
